# Generated by Django 3.2.8 on 2021-12-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0003_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='who_are_you',
            field=models.CharField(choices=[('influencer', 'Influencer'), ('content_creator', 'Content Creator'), ('youtuber', 'Youtuber'), ('web_developer', 'Web Developer'), ('graphics_designer', 'Graphics Designer'), ('teacher', 'Teacher'), ('student', 'Student')], default='influencer', max_length=30),
        ),
    ]
