# Generated by Django 3.2.8 on 2021-12-29 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0005_alter_projectmodel_project_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(blank=True, max_length=200, null=True)),
                ('blog_description', models.TextField(blank=True, null=True)),
                ('blog_thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('blog_category', models.TextField(blank=True, max_length=50, null=True)),
                ('blog_tags', models.TextField(blank=True, null=True)),
                ('blog_created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mycv.profile')),
            ],
        ),
    ]
