# Generated by Django 3.2.8 on 2021-12-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0006_blogmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='blog_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='blog_tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
